### ISSUE TITLE
This isn't an issue, but what is the benefit of this patcher?

### ISSUE THREAD

**Issue by ghyujkilop** [Deigue/CellEditorIDFixer#2]
Does it also kill any mod compatibility?

**Comment by seancojr** [comment]
> Does it also kill any mod compatibility?

For posterity sake and because I had this question before, I'll explain what I discovered. A [user post](https://www.reddit.com/r/skyrimmods/comments/5fvul2/underscores_in_cell_editor_ids_break_save_sorting/) on Reddit explains the underscores present in cell IDs can can break save sorting in Skyrim SE. In other words, certain save game files will not appear under the character name menu when attempting to load a save. To answer the question about mod compatibility, it is completely safe to change the editor IDs of plugin records as was discussed on the [Nexus Forums](https://forums.nexusmods.com/index.php?/topic/7055201-a-simple-question-about-changing-the-editor-id-of-an-object/).

**Comment by Deigue** [comment]
Yes, @seancojr has explained it pretty well. If you try to save the game in a Cell/Worldspace where an underscore is present, the naming convention of the save game name will be weird/off (since the segments of the name of the save file , timestamp/date etc are underscore delimited). This just rectifies that and ensures its all good.

**Comment by Deigue** [comment]
As for a direct answer to your initial question, no it will not kill mod compatibility.
